### PR TITLE
Update to OC 1.5

### PR DESCRIPTION
**Pull request by gamax92**

### CODE REVIEW

**Comment by fnuecke** [comment]
Is the gradlew.bat only line ending changes or what? >_>

**Comment by gamax92** [comment]
I'll go and fix that

**Comment by gamax92** [comment]
Fixed that. The change was technically correct though, it currently has linux endings which is wrong for a batch file.

**Comment by fnuecke** [comment]
Ah I see; well, git will usually autoconvert that so eh (actually it'd probably have converted it back for me at some point :X).

**Pull request merged**
